// ── Design tokens ────────────────────────────────────────────────────────────
export const C = {
  bg: 'var(--theme-bg)',
  surface: 'var(--theme-surface)',
  surfaceHover: 'var(--theme-surface-hover)',
  border: 'var(--theme-border)',
  text: 'var(--theme-text)',
  textMuted: 'var(--theme-text-muted)',
  primary: 'var(--theme-primary)',
  primaryLight: 'var(--theme-primary-light)',
  primaryAlpha: 'var(--theme-primary-alpha)',
  cyan: 'var(--theme-cyan)',
  green: 'var(--theme-green)',
  greenAlpha: 'var(--theme-green-alpha)',
  red: 'var(--theme-red)',
  redAlpha: 'var(--theme-red-alpha)',
  amber: 'var(--theme-amber)',
  blue: 'var(--theme-blue)',
} as const;

export const S = {
  card: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: 12,
    padding: 20,
  } as React.CSSProperties,
  btn: (color: string = C.primary): React.CSSProperties => ({
    background: color,
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '8px 16px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
  }),
  btnOutline: (color: string = C.primary): React.CSSProperties => ({
    background: 'transparent',
    color: color,
    border: `1px solid ${color}`,
    borderRadius: 8,
    padding: '8px 16px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
  }),
  badge: (color: string, alphaColor?: string): React.CSSProperties => ({
    background: alphaColor || `color-mix(in srgb, ${color} 15%, transparent)`,
    color: color,
    borderRadius: 20,
    padding: '2px 10px',
    fontSize: 11,
    fontWeight: 700,
    display: 'inline-block',
  }),
} as const;
