// ── Design tokens ────────────────────────────────────────────────────────────
export const C = {
  bg: 'var(--theme-bg)',
  surface: 'var(--theme-surface)',
  surfaceHover: 'var(--theme-surface-hover)',
  surfaceAlt: 'var(--theme-surface-alt)',
  border: 'var(--theme-border)',
  borderLight: 'var(--theme-border-light)',
  text: 'var(--theme-text)',
  textMuted: 'var(--theme-text-muted)',
  primary: 'var(--theme-primary)',
  primaryLight: 'var(--theme-primary-light)',
  primaryDark: 'var(--theme-primary-dark)',
  primaryAlpha: 'var(--theme-primary-alpha)',
  cyan: 'var(--theme-cyan)',
  green: 'var(--theme-green)',
  greenAlpha: 'var(--theme-green-alpha)',
  red: 'var(--theme-red)',
  redAlpha: 'var(--theme-red-alpha)',
  amber: 'var(--theme-amber)',
  blue: 'var(--theme-blue)',
} as const;

export const S = {
  card: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: 'var(--radius-lg)',
    padding: 24,
    boxShadow: 'var(--shadow-sm)',
  } as React.CSSProperties,
  btn: (color: string = C.primary): React.CSSProperties => ({
    background: color,
    color: '#fff',
    border: 'none',
    borderRadius: 'var(--radius-sm)',
    padding: '8px 16px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'inherit',
    letterSpacing: '0.01em',
    transition: 'all 0.15s ease',
  }),
  btnOutline: (color: string = C.primary): React.CSSProperties => ({
    background: 'transparent',
    color: color,
    border: `1px solid ${color}`,
    borderRadius: 'var(--radius-sm)',
    padding: '8px 16px',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: 'inherit',
    letterSpacing: '0.01em',
    transition: 'all 0.15s ease',
  }),
  badge: (color: string, alphaColor?: string): React.CSSProperties => ({
    background: alphaColor || `color-mix(in srgb, ${color} 12%, transparent)`,
    color: color,
    borderRadius: 'var(--radius-sm)',
    padding: '3px 10px',
    fontSize: 11,
    fontWeight: 600,
    display: 'inline-block',
    letterSpacing: '0.02em',
    lineHeight: '16px',
  }),
  input: {
    width: '100%',
    background: C.bg,
    border: `1px solid ${C.border}`,
    borderRadius: 'var(--radius-sm)',
    padding: '9px 12px',
    color: C.text,
    fontSize: 13,
    fontFamily: 'inherit',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.15s ease, box-shadow 0.15s ease',
  } as React.CSSProperties,
} as const;
