-- Add new MerchantCategory enum values (idempotent via IF NOT EXISTS)
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'BOUCHERIE';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'PATISSERIE';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'FASTFOOD';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'HAMMAM';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'ANIMALERIE';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'FLEURISTE';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'BIJOUTERIE';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'OPTIQUE';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'TELEPHONE';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'BRICOLAGE';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'AUTO';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'HOTEL';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'PARFUMERIE';
ALTER TYPE "MerchantCategory" ADD VALUE IF NOT EXISTS 'TRAITEUR';
